name: XanApi
version: ${project.version}
main: onxansde.xanapi.XanApi
api-version: 1.16
authors: [ onXans ]
description: Needed for a lot of Plugins by onXans
commands:
  xanapi:
    description: Change Settings and reload Config